//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Update.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;压缩文件|*.zip&quot;.
        /// </summary>
        internal static string strFilter {
            get {
                return ResourceManager.GetString("strFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string strTip {
            get {
                return ResourceManager.GetString("strTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本已经是最新版本.
        /// </summary>
        internal static string strTip1 {
            get {
                return ResourceManager.GetString("strTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到新版本，是否下载？.
        /// </summary>
        internal static string strTip2 {
            get {
                return ResourceManager.GetString("strTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新已下载，更新请退出已启动的ADB!.
        /// </summary>
        internal static string strTip3 {
            get {
                return ResourceManager.GetString("strTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装已取消，您可以将解压安装目录下的ADB_Uptade.zip并覆盖原安装文件手动更新.
        /// </summary>
        internal static string strTip4 {
            get {
                return ResourceManager.GetString("strTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新已安装，是否启动程序？.
        /// </summary>
        internal static string strTip5 {
            get {
                return ResourceManager.GetString("strTip5", resourceCulture);
            }
        }
    }
}
