namespace MsHtmHstInterop
{
    using System;

    public enum tagDOCHOSTUIFLAG
    {
        DOCHOSTUIFLAG_ACTIVATE_CLIENTHIT_ONLY = 0x200,
        DOCHOSTUIFLAG_CODEPAGELINKEDFONTS = 0x800,
        DOCHOSTUIFLAG_DIALOG = 1,
        DOCHOSTUIFLAG_DISABLE_EDIT_NS_FIXUP = 0x400000,
        DOCHOSTUIFLAG_DISABLE_HELP_MENU = 2,
        DOCHOSTUIFLAG_DISABLE_OFFSCREEN = 0x40,
        DOCHOSTUIFLAG_DISABLE_SCRIPT_INACTIVE = 0x10,
        DOCHOSTUIFLAG_DIV_BLOCKDEFAULT = 0x100,
        DOCHOSTUIFLAG_ENABLE_FORMS_AUTOCOMPLETE = 0x4000,
        DOCHOSTUIFLAG_ENABLE_INPLACE_NAVIGATION = 0x10000,
        DOCHOSTUIFLAG_FLAT_SCROLLBAR = 0x80,
        DOCHOSTUIFLAG_IME_ENABLE_RECONVERSION = 0x20000,
        DOCHOSTUIFLAG_NO3DBORDER = 4,
        DOCHOSTUIFLAG_NO3DOUTERBORDER = 0x200000,
        DOCHOSTUIFLAG_NOPICS = 0x100000,
        DOCHOSTUIFLAG_NOTHEME = 0x80000,
        DOCHOSTUIFLAG_OPENNEWWIN = 0x20,
        DOCHOSTUIFLAG_OVERRIDEBEHAVIORFACTORY = 0x400,
        DOCHOSTUIFLAG_SCROLL_NO = 8,
        DOCHOSTUIFLAG_THEME = 0x40000,
        DOCHOSTUIFLAG_URL_ENCODING_DISABLE_UTF8 = 0x1000,
        DOCHOSTUIFLAG_URL_ENCODING_ENABLE_UTF8 = 0x2000
    }
}

